03_Django/CRUD_COPY/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

03_Django/CRUD_COPY/jobs/models.py
from django.db import models

class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    def __str__(self):
        return self.name

03_Django/CRUD_COPY/jobs/views.py
from django.shortcuts import render, redirect
from .models import Job
from faker import Faker
from decouple import config
import requests

def index(request):
    return render(request, 'jobs/index.html')


def past_life(request):
    name = request.POST.get('name')
    person = Job.objects.filter(name=name).first()
    # filter 는 값이 없어도 에러가 나지 않음

    # DB에 이름이 있을 경우
    if person:
        past_job = person.past_job
    # DB에 이름이 없을 경우
    else:
        fake = Faker()
        # 랜덤 직업 생성
        past_job = fake.job()
        # 새로운 이름, 직업 추가 후 DB 저장
        person = Job(name=name, past_job=past_job)
        person.save()

    # GIPHY
    #1. API key 가져오기
    GIPHY_API_KEY = config('GIPHY_API_KEY')
    #2. 요청 URL 세팅
    url = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API_KEY}&q={past_job}&limit=1'
    #3. 실제 요청을 보내자 (json -> dict)
    data = requests.get(url).json()
    #4. image 추출
    try:
        image = data.get('data')[0].get('images').get('original').get('url')
    except IndexError:
        image = None

    # context = {'person': person, 'image': image}
    # return render(request, 'jobs/past_life.html', context)


    # NAVER IMAGE
    #1. 요청 헤더 정보 준비
    NAVER_ID = config('NAVER_ID')
    NAVER_SECRET = config('NAVER_SECRET')

    headers = {'X-Naver-Client-Id': NAVER_ID,
            'X-Naver-Client-Secret': NAVER_SECRET,}

    #2. 요청 URL 준비
    naver_url = f'https://openapi.naver.com/v1/search/image?query={past_job}&filter=medium&display=1'

    #3. 실제 요청 보내기
    naver_data = requests.get(naver_url, headers=headers).json()
    print(naver_data)

    #4. 이미지 링크 추출하기
    naver_image = naver_data.get('items')[0].get('link')

    context = {'person':person, 'image': image, 'naver_image': naver_image,}

    return render(request, 'jobs/past_life.html', context)

03_Django/CRUD_COPY/jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block body %}
    <h1 class="text-center">전생의 직업은...?</h1>
    <h2 class="text-center">당신의 전생 직업을 알려드립니다.</h2>
    <hr>

    <form action="{% url 'jobs:past_life' %}" method="POST">
        {% csrf_token %}
        <label for="name">NAME</label><br>
        <input type="text" name="name" id="name"><br>
        <input type="submit" value="이름 전송">
    </form>
{% endblock %}

03_Django/CRUD_COPY/jobs/templates/jobs/past_life.html
{% extends 'base.html' %}

{% block body %}
<h2 class="text-center">{{ person.name }} 님의 전생 직업은 {{ person.past_job }} 입니다.</h2>
<h3 class="text-center">GIPHY</h3>
<img src="{{ image }}" alt="giphy-image">

<a href="{% url 'jobs:index' %}">내 전생에 또 다른 직업이 있을까?</a>
{% endblock %}