03_Django/pair-programming/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments_create/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/<int:comment_pk>/comments_delete', views.comments_delete, name='comments_delete'),
]

03_Django/pair-programming/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk',]


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk',]

03_Django/pair-programming/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'content', }

03_Django/pair-programming/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from IPython import embed
from django.views.decorators.http import require_POST
import bootstrap4


def index(request):
    articles = Article.objects.all()
    context = {'articles': articles, }
    # embed()
    return render(request, 'articles/index.html', context)


def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST)
        article = article_form.save()
        return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm()
    context = {'article_form': article_form, }
    return render(request, 'articles/create.html', context)


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.comments.all()
    comment_form = CommentForm()
    context = {'article': article, 'comments': comments, 'comment_form': comment_form, }
    return render(request, 'articles/detail.html', context)


def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    # article_form = ArticleForm(instance=article)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=article)
        article_form.save()
        return redirect('articles:detail', article_pk)
    # article_form = ArticleForm(Article, instance=article)
    else:
        article_form = ArticleForm(instance=article)
        context = {'article_form': article_form, 'article': article, }
        return render(request, 'articles/create.html', context)

@require_POST
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('articles:index')


def comments_create(request, article_pk):
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        comment = comment_form.save(commit=False)
        comment.article_id = article_pk
        comment.save()
        return redirect('articles:detail', article_pk)
    comment_form = CommentForm()
    context = {'comment_form':comment_form, }
    return render(request, 'articles/detail.html', context)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)
    

03_Django/pair-programming/articles/templates/articles/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% bootstrap_css %}
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    {% block body %}
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

03_Django/pair-programming/articles/templates/articles/create.html
{% extends 'articles/base.html' %}

{% block body %}
    
    {% if request.resolver_match.url_name == 'create' %}
    <h2 class="text-center">CREATE</h2>
    {%  else %}
    <h2 class="text-center">UPDATE</h2>
    {% endif %}
    <br>
    <hr>
    <br>
    {% if request.resolver_match.url_name == 'create' %}
        <form action="{% url 'articles:create' %}" method="POST">
            {% csrf_token %}
            {{ article_form.as_p }}
            <input type="submit" value="작성" class="btn btn-primary">
        </form>
    {% else %}
        <form action="{% url 'articles:update' article.pk %}" method="POST">
            {% csrf_token %}
            {{ article_form.as_p }}
            <input type="submit" value="수정" class="btn btn-success">
        </form>
    {% endif %}
        
    
{% endblock %}

03_Django/pair-programming/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}

{% block body %}
<h2 class="text-center">DETAIL</h2>
<hr>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <p>작성 시간: {{ article.created_at }}</p>
    <p>수정 시간: {{ article.updated_at }}</p>
    <a href="{% url 'articles:update' article.pk %}" class="btn btn-success">글 수정</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글 삭제" class="btn btn-danger">
    </form>
<hr>
<p><b>새 댓글</b></p>
<form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="댓글 입력" class="btn btn-dark">
</form>
<hr>
<p><b>댓글 목록</b></p>
<p><b>현재까지 댓글 수 : {{ comments.count }}</b></p>  
    {% for comment in comments %}
        <hr>
        <p>{{ comment.pk }}번 댓글: {{ comment.content }}</p>
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="댓글 삭제" class="btn btn-warning">
        </form>
    {% endfor %}
<hr>
<a href="{% url 'articles:index' %}">[메인 페이지로]</a>
{% endblock %}

03_Django/pair-programming/articles/templates/articles/index.html
{% extends 'articles/base.html' %}

{% block body %}
    <h2 class="text-center">ARTICLES</h2>
    <br><br>
    <h4>새 글 작성</h4>
    <a href="{% url 'articles:create' %}" class="btn btn-light">새 글 작성하기</a>
    {% for article in articles %}
        <hr>
        <p><b>[ {{ article.pk }}번 글 ]</b></p>
        <p>▶ 제목: {{ article.title }}</p>
        <a href="{% url 'articles:detail' article.pk %}">[상세 글 보기]</a>
        {% empty %}
        <p>작성된 게시글이 없습니다.</p>
    {% endfor %}



{% endblock %}