03_Django/09_django_axios/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # string은 <str: > 명시 안해주고 아래처럼 쓰면 됨
    path('<username>/', views.profile, name='profile'),
]

03_Django/09_django_axios/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments_create', views.comments_create, name='comments_create'),
    path('<int:article_pk>/<int:comment_pk>/comments_delete', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/<int:comment_pk>/comments_update', views.comments_update, name='comments_update'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
]

03_Django/09_django_axios/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

03_Django/09_django_axios/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

03_Django/09_django_axios/articles/models.py
from django.db import models
from django.conf import settings


class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_articles", blank=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)

    class Meta:
        ordering = ('-pk', )

    def __str__(self):
        return self.title

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk', )

    def __str__(self):
        return f'<Article({self.article_id}): Comment({self.pk} - {self.content})'

03_Django/09_django_axios/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # 커스텀하려면 USER 모델은 직접 참조하면 안된다.
        fields = ('email', 'first_name', 'last_name', )


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email', )

03_Django/09_django_axios/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm
from IPython import embed

def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            # embed()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()

    context = {'form': form, }
    return render(request, 'accounts/auth_form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # user = form.get_user()
            auth_login(request, form.get_user())
            # embed()
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {'form': form, }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('articles:index')


@require_POST
def delete(request):
    request.user.delete()
    return redirect('articles:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form, }
    return render(request, 'accounts/auth_form.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form, }
    return render(request, 'accounts/auth_form.html', context)


def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username) # 여기서는 모델을 가져와야함. (AUTH_USER_MODEL 이건 스트링!)
    # embed()
    context = {'person': person, }
    return render(request, 'accounts/profile.html', context)

03_Django/09_django_axios/accounts/templates/accounts/auth_form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if request.resolver_match.url_name == 'signup' %}
    <h1>SIGNUP</h1>
{% elif request.resolver_match.url_name == 'update' %}
    <h1>USER UPDATE</h1>
{% else %}
    <h1>CHANGE_PASSWORD</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="Submit" reset="Cancel"%}{% endbuttons %}
</form>
{% endblock %}

03_Django/09_django_axios/accounts/templates/accounts/login.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block body %}
<h1>LOGIN</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="Submit" reset="Cancel"%}{% endbuttons %}
</form>
<a href="{% provider_login_url 'kakao' %}" class="btn btn-warning">KAKAO LOGIN</a>
{% endblock %}

03_Django/09_django_axios/accounts/templates/accounts/profile.html
{% extends 'articles/base.html' %}
{% block body %}

<h1 class="text-center">{{ person.username }}'s Profile</h1>
<hr>
<h3 class="text-center">{{ person.username }}이 작성한 글</h3>
<div class="row">
    {% with articles=person.article_set.all %}
        {% for article in articles|dictsortreversed:"pk" %}
        <div class="col-4 my-2">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ article.content }}</h5>
                    <p class="card-text">{{ article.like_users.count }}명이 좋아하는 글</p>
                    <p class="card-text">{{ article.comment_set.count }}개의 댓글</p>
                    <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">상세글 보러가기</a>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endwith %}
    </div>
    <hr>
    <h3 class="text-center">{{ person.username }}이 작성한 댓글</h3>
    <div class="row">
    {% with comments=person.comment_set.all %}
        {% for comment in comments|dictsortreversed:"pk" %}
        <div class="col-4 my-2">
            <div class="card">
                <div class="card-body">
                    <blockquote class="blockquote">
                        <p class="mb-0">{{ comment.content }}</p>
                        <footer class="blockquote-footer">{{ comment.created_at|date:"SHORT_DATE_FORMAT" }}</footer>
                    </blockquote>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endwith %}
</div>

{% endblock %}