03_Django/05_django_crud_prac/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'), # GET
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'), # GET(new), POST(create)
    path('<int:pk>/', views.detail, name='detail'), # GET
    path('<int:pk>/delete/', views.delete, name='delete'), # POST
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'), # GET(edit), POST(update)
]

03_Django/05_django_crud_prac/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'제목: {self.title}, 내용: {self.content}'

03_Django/05_django_crud_prac/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from IPython import embed

def index(request):
    print(request.method)
    articles = Article.objects.order_by('-pk')
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)

def new(request):
    embed()
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    embed()
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

03_Django/05_django_crud_prac/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">DETAIL</h2>
    <h3>{{ article.pk }}번째 글</h3>
    <hr>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <p>글 생성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
    <p>글 수정 시각: {{ article.updated_at|date:"M, j, Y" }}</p>
    <hr>
    <!-- <a href="/articles/{{ article.pk }}/edit/">[글 수정]</a> -->
    <a href="{% url 'articles:edit' article.pk %}">[글 수정]</a>
    <!-- <a href="/articles/{{ article.pk }}/delete/">[글 삭제]</a><br> -->
    <a href="{% url 'articles:delete' article.pk %}">[글 삭제]</a><br>
    <!-- <a href="/articles/">[메인 페이지]</a> -->
    <a href="{% url 'articles:index' %}">[메인 페이지]</a>
{% endblock %}

03_Django/05_django_crud_prac/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">EDIT</h2>
    <form action="{% url 'articles:update' article.pk %}" method=POST>
        {% csrf_token %}
        <label for="title">글 제목: </label><br>
        <input type="text" name="title" id="title" value="{{ article.title }}"><br>
        <label for="content">글 내용: </label><br>
        <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea><br>
        <input type="submit" value="글 수정">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[메인 페이지]</a>
{% endblock %}

03_Django/05_django_crud_prac/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">Articles</h2>
    {% for article in articles %}
        <p>글 번호: {{ article.id }}</p>
        <p>글 제목: {{ article.title }}</p>
        <p>글 내용: {{ article.content }}</p>
        <a href="{% url 'articles:detail' article.pk %}">[상세보기]</a>
        <hr>
    {% endfor %}
    <a href="{% url 'articles:new' %}">[글 작성]</a>
{% endblock %}

03_Django/05_django_crud_prac/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block body %}
    <h2 class="text-center">NEW</h2>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <label for="title">글 제목: </label><br>
        <input type="text" name="title" id="title"><br>
        <label for="content">글 내용: </label><br>
        <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
        <input type="submit" value="글 작성">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[메인 페이지]</a>
{% endblock %}